version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    build:
      context: .
    container_name: jenkins
    user: root
    privileged: true
    ports:
      - 9090:8080
      - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      

# docker-compose up
# docker-compose up -d
# docker-compose -f docker-compose-custom.yml up


# 이미지 생성 명령어 (현 파일과 같은 디렉토리에서)
# docker build -t {이미지명} .

# 컨테이너 생성 & 실행 명령어
# docker run --name {컨테이너명} -p 80:80 -d {이미지명}

# docker build -t httpd-img .
# docker run --name httpd-con -p 80:80 -d httpd-img

# docker inspect httpd-con
# docker exec -it httpd-con bash
